spring:
  flyway:
    enabled: true
    table: migration_history
    schemas: ${db.name}
    datasource:
      jdbc-url: jdbc:mysql://${db.host}:${db.port}/${db.name}?serverTimezone=UTC&user=${db.credentials.username}&password=${db.credentials.password}
      jpa:
        properties:
          hibernate:
            show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: '@spring.profiles.active@'

jwt:
  signature:
    secret: ybh3+N9auwFTcqOGl0AEE1GbPf27ivTTmgzGK3P8oS+vcY1PXV6feI2gz1dX3a3yayVvdE5ONiIwDsLZf7rOwg==
    algorithm: HS512
  claim:
    iss: www.peachy-mind.com
    lifetime: 10080 #mins