spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    table: migration_history
    schemas: ${db.primary}
    default-schema: ${db.primary}
  profiles:
    active: dev

token:
  jwt:
    refresh:
      prefix: Refresh
      signature:
        secret: QcbQuxZHPyzgBAqJbOrJM94RQzXDF+I2IIk4+OIrmMbh7q133CaMIt7OqqaCIBAxF6+S3Iyy1n7CrimB8qZPlA==
        algorithm: HS512
      claim:
        lifetime: 2678400 #seconds
    prefix: Bearer
    signature:
      secret: ybh3+N9auwFTcqOGl0AEE1GbPf27ivTTmgzGK3P8oS+vcY1PXV6feI2gz1dX3a3yayVvdE5ONiIwDsLZf7rOwg==
      algorithm: HS512
    claim:
      iss: www.peachy-mind.com
      lifetime: 604200 #seconds
  internal:
    prefix: Internal
    signature:
      secret: 8QwetCf03dqdQ6WhlBbisCMv3haagarVCbjJXv7xJE9X3uBD1wcjEnUCkbANmXal5O1LfnI2+mCjmvv4w5Cq3Q==
      algorithm: HS512
    claim:
      iss: www.peachy-mind.com
      lifetime: 604800 #seconds

gateway:
  serviced-application-names: peachy-mind