server:
  port: ${self.port}

spring:
  flyway:
    enabled: true
    table: migration_history
    schemas: ${db.name}
  datasource:
    jdbc-url: jdbc:mysql://${db.host}:${db.port}/${db.name}?serverTimezone=UTC&user=${db.credentials.username}&password=${db.credentials.password}
    jpa:
      properties:
        hibernate:
          show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: '@spring.profiles.active@'

token:
  jwt:
    refresh:
      prefix: Refresh
      signature:
        secret: QcbQuxZHPyzgBAqJbOrJM94RQzXDF+I2IIk4+OIrmMbh7q133CaMIt7OqqaCIBAxF6+S3Iyy1n7CrimB8qZPlA==
        algorithm: HS512
      claim:
        lifetime: 44640 #mins
    prefix: Bearer
    signature:
      secret: ybh3+N9auwFTcqOGl0AEE1GbPf27ivTTmgzGK3P8oS+vcY1PXV6feI2gz1dX3a3yayVvdE5ONiIwDsLZf7rOwg==
      algorithm: HS512
    claim:
      iss: www.peachy-mind.com
      lifetime: 10080 #mins
  internal:
    prefix: Internal
    signature:
      secret: 8QwetCf03dqdQ6WhlBbisCMv3haagarVCbjJXv7xJE9X3uBD1wcjEnUCkbANmXal5O1LfnI2+mCjmvv4w5Cq3Q==
      algorithm: HS512
    claim:
      iss: www.peachy-mind.com
      lifetime: 10090 #mins

gateway:
  serviced-application-names: peachy-mind