self:
  port: 8090
  course:
    border-grade: 80

spring:
  flyway:
    default-schema: peachy_mind
    schemas: peachy_mind
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
  application:
    name: peachy-mind

eureka:
  instance:
    status-page-url-path: http://${self.host}:${self.port}/general/health
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${discovery.host}:${discovery.port}/eureka