server:
  port: 8090

self:
  course:
    border-grade: 80

spring:
  flyway:
    default-schema: peachy_mind
    schemas: peachy_mind
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
  application:
    name: peachy-mind

eureka:
  instance:
    status-page-url-path: http://localhost:${self.port}
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: ${discovery.uri}/eureka