server:
  port: ${random.server.port}
spring:
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
  application:
    name: peachy-mind
  flyway:
    enabled: true
    table: migration_history
  datasource:
    jdbc-url: jdbc:mysql://${db.credentials.domain}:${db.credentials.port}/${db.name}?serverTimezone=UTC&user=${db.credentials.username}&password=${db.credentials.pass}
    jpa:
      properties:
        hibernate:
          show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: '@spring.profiles.active@'
eureka:
  instance:
    status-page-url-path: http://localhost:${server.port}/health
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8200/eureka
default:
  signature-algorithm:
    value: ${default.signature-algorithm.hs512}
    hs512: HS512
  secret:
    value: ${default.secret.hs512}
    hs512: ybh3+N9auwFTcqOGl0AEE1GbPf27ivTTmgzGK3P8oS+vcY1PXV6feI2gz1dX3a3yayVvdE5ONiIwDsLZf7rOwg==