spring:
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
  application:
    name: peachy-mind

eureka:
  instance:
    status-page-url-path: http://${self.host}:${self.port}/health
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka