self:
  port: 8200

spring:
  cloud:
    bus:
      id: ${spring.application.name}:${random.value}
  application:
    name: peachy-mind-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${self.host}:${self.port}/eureka