self:
  port: 8500

spring:
  cloud:
    bus:
      id: ${eureka.instance.instance-id}
  application:
    name: peachy-mind-gateway

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

eureka:
  instance:
    status-page-url-path: http://${self.host}:${self.port}/general/health
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://${discovery.host}:${discovery.port}/eureka

token:
  jwt:
    claim:
      iss: gateway

brute-force:
  protection:
    auth-attempt:
      limit:
        count: 10
        ttl: 1200 #seconds
