server:
  port: 8300

spring:
  application:
    name: peachy-mind-gateway

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

eureka:
  instance:
    status-page-url-path: ${self.uri}/general/health
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: ${discovery.uri}/eureka

gateway:
  serviced-application-names: peachy-mind

brute-force:
  protection:
    auth-attempt:
      limit:
        count: 10
        ttl: 1200 #seconds
      pre-limit:
        ttl: 180 #seconds
